### ISSUE TITLE
Server aufsetzen

### ISSUE THREAD

**Issue by Donskelle** [Donskelle/Web-SystemeFL#2]
Anforderungen:
- Socket IO
- PHP Version 5.X
- Download Link adden

**Comment by JanUrb** [comment]
Meinst du als VM aufsetzten?

Edit: Das Github Student Pack bietet Credit für Hosting bei Digital Ocean an. Eventuell ist das eine Option.

**Comment by Donskelle** [comment]
Ja genau. Aber das wird erst interessant, wenn wir wissen, welche Technologien wir verwenden.

Von: KratBro [mailto:notifications@github.com] 
Gesendet: Montag, 23. März 2015 19:18
An: Donskelle/Web-SystemeFL
Cc: Donskelle
Betreff: Re: [Web-SystemeFL] Server aufsetzen (#2)

Meinst du als VM aufsetzten?

**Comment by ZeroPit** [comment]
Laravel Installiert und Layout erstellt

**Comment by ZeroPit** [comment]
Typo3 Neos Installiert

**Comment by ZeroPit** [comment]
Sphinx Installiert
HTML und PDF Erstellung Läuft

**Comment by ZeroPit** [comment]
VM Aufgesetzt und ist im Netzt wenn mein PC an ist 
steensen.selfhost.eu:800
